update 20260305_0926_en

diff --git a/funclist-en b/funclist-en
--- a/funclist-en
+++ b/funclist-en
@@ -454,3 +454,25 @@ ncd() {
 # 	for DDD in majbin majrcs metsys; do check-git-diffs-en $DDD; done
 # }
 
+# 20260304
+# vim filename, but create filename-backup first
+vimb() {
+	if [ $# -ne 1 ]; then
+		vim
+	else
+		local fname="$1"
+		if [ ! -f "${fname}" ]; then
+			echo "[ERROR] no such file"
+			exit 1
+		fi
+
+		if [ -f "${fname}-backup" ]; then
+			echo "[INFO] backup file already exists"
+			vim "${fname}"
+		else
+			cp -v "${fname}" "${fname}-backup"
+			vim "${fname}"
+		fi
+	fi
+}
+
